### ISSUE TITLE
Support of Shelly EM Gen1 device with the Shelly3EmExporter

### ISSUE THREAD

**Issue by jfallot** [lukassoo/ShellyExporters#10]
Hello,

I noticed that it is possible to collect metrics from a Shelly EM Gen1 device with the Shelly3EmExporter by monitoring only 2 indexes and not collecting the current.
Here an excerpt of the Shelly3EmExporter config for a Shelly EM:

```
  targetMeters:
  - index: 0
    ignorePower: false
    ignoreVoltage: false
    ignoreCurrent: true
    ignorePowerFactor: false
    ignoreTotal: false
    ignoreTotalReturned: false
  - index: 1
    ignorePower: false
    ignoreVoltage: false
    ignoreCurrent: true
    ignorePowerFactor: false
    ignoreTotal: false
    ignoreTotalReturned: false
  ignoreRelayStateMetric: false
``` 

From the documentation of the Shelly EM Gen1 API at https://shelly-api-docs.shelly.cloud/gen1/#shelly-em-emeter-index, you can notice that no current is returned, but we have an additional "reactive" attribute returning the "Instantaneous reactive power".

I am then wondering about the best way to officially support this device and compute a current:
* Improve this Shelly3EmExporter to collect the "reactive" metric when available and compute the current when it is not available (based on the power, voltage and the power factor)
* Or rather do so through a new exporter?

Thanks
